// <auto-generated />
using System;
using HR_KD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HR_KD.Migrations
{
    [DbContext(typeof(HrDbContext))]
    [Migration("20250430103032_AddIsActiveInMucLuongToiThieu")]
    partial class AddIsActiveInMucLuongToiThieu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HR_KD.Data.BangLuong", b =>
                {
                    b.Property<int>("MaLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLuong"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("LuongTangCa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LuongThem")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    b.Property<decimal>("PhuCapThem")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("ThangNam")
                        .HasColumnType("date");

                    b.Property<decimal>("ThucNhan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ThueTNCN")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TongLuong")
                        .HasColumnType("decimal(20, 2)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chưa Thanh Toán");

                    b.HasKey("MaLuong")
                        .HasName("PK__BangLuon__6609A48DC1CE160C");

                    b.HasIndex("MaNv");

                    b.ToTable("BangLuong", (string)null);
                });

            modelBuilder.Entity("HR_KD.Data.CauHinhLuongThue", b =>
                {
                    b.Property<int>("MaCauHinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCauHinh"));

                    b.Property<decimal>("GiaTri")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("MucLuongDen")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MucLuongTu")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaCauHinh")
                        .HasName("PK__CauHinhL__F0685B7DE11C888F");

                    b.ToTable("CauHinhLuongThue", (string)null);
                });

            modelBuilder.Entity("HR_KD.Data.ChamCong", b =>
                {
                    b.Property<int>("MaChamCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChamCong"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<TimeOnly?>("GioRa")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("GioVao")
                        .HasColumnType("time");

                    b.Property<int>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    b.Property<DateOnly>("NgayLamViec")
                        .HasColumnType("date");

                    b.Property<decimal?>("TongGio")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chưa Duyệt");

                    b.HasKey("MaChamCong")
                        .HasName("PK__ChamCong__307331A168A5D6B5");

                    b.HasIndex("MaNv");

                    b.ToTable("ChamCong", null, t =>
                        {
                            t.HasTrigger("trg_InsertLichSuChamCong");

                            t.HasTrigger("trg_UpdateTongGio");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("HR_KD.Data.ChiTietDanhGium", b =>
                {
                    b.Property<int>("MaChiTietDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietDanhGia"));

                    b.Property<decimal?>("DiemDanhGia")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("MaDanhGia")
                        .HasColumnType("int");

                    b.Property<int?>("MaTieuChiDanhGia")
                        .HasColumnType("int");

                    b.Property<string>("NhanXet")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaChiTietDanhGia")
                        .HasName("PK__ChiTietD__CC6E45534F93654C");

                    b.HasIndex("MaDanhGia");

                    b.HasIndex("MaTieuChiDanhGia");

                    b.ToTable("ChiTietDanhGia");
                });

            modelBuilder.Entity("HR_KD.Data.ChucVu", b =>
                {
                    b.Property<int>("MaChucVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChucVu"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaChucVu")
                        .HasName("PK__ChucVu__D4639533E0783BE9");

                    b.ToTable("ChucVu", (string)null);
                });

            modelBuilder.Entity("HR_KD.Data.DanhGiaNhanVien", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<decimal?>("DiemDanhGia")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int?>("MaNguoiDanhGia")
                        .HasColumnType("int");

                    b.Property<int>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    b.Property<DateOnly>("NgayDanhGia")
                        .HasColumnType("date");

                    b.Property<string>("NhanXet")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaDanhGia")
                        .HasName("PK__DanhGiaN__AA9515BF62111141");

                    b.HasIndex("MaNguoiDanhGia");

                    b.ToTable("DanhGiaNhanVien", (string)null);
                });

            modelBuilder.Entity("HR_KD.Data.DaoTao", b =>
                {
                    b.Property<int>("MaDaoTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDaoTao"));

                    b.Property<int>("MaPhongBan")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.Property<string>("TenDaoTao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaDaoTao")
                        .HasName("PK__DaoTao__81987A7CE02F6E17");

                    b.HasIndex("MaPhongBan");

                    b.ToTable("DaoTao", (string)null);
                });

            modelBuilder.Entity("HR_KD.Data.LichSuChamCong", b =>
                {
                    b.Property<int>("MaLichSuChamCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichSuChamCong"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly?>("GioRa")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("GioVao")
                        .HasColumnType("time");

                    b.Property<int>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    b.Property<DateOnly>("Ngay")
                        .HasColumnType("date");

                    b.Property<decimal?>("TongGio")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chưa Duyệt");

                    b.HasKey("MaLichSuChamCong")
                        .HasName("PK__LichSuCh__66853896CB759516");

                    b.HasIndex("MaNv");

                    b.ToTable("LichSuChamCong", (string)null);
                });

            modelBuilder.Entity("HR_KD.Data.LichSuDaoTao", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichSu"));

                    b.Property<string>("KetQua")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaDaoTao")
                        .HasColumnType("int");

                    b.Property<int>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    b.HasKey("MaLichSu")
                        .HasName("PK__LichSuDa__C443222A500F5F13");

                    b.HasIndex("MaDaoTao");

                    b.HasIndex("MaNv");

                    b.ToTable("LichSuDaoTao", (string)null);
                });

            modelBuilder.Entity("HR_KD.Data.LoaiHopDong", b =>
                {
                    b.Property<int>("MaLoaiHopDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiHopDong"));

                    b.Property<int?>("GiaHanToiDa")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenLoaiHopDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ThoiHanMacDinh")
                        .HasColumnType("int");

                    b.Property<double?>("TiLeLuong")
                        .HasColumnType("float");

                    b.HasKey("MaLoaiHopDong");

                    b.ToTable("LoaiHopDongs");
                });

            modelBuilder.Entity("HR_KD.Data.LoaiNgayNghi", b =>
                {
                    b.Property<int>("MaLoaiNgayNghi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiNgayNghi"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLoaiNgayNghi")
                        .HasName("PK__LoaiNgay__3E18383F70879B53");

                    b.ToTable("LoaiNgayNghi", (string)null);
                });

            modelBuilder.Entity("HR_KD.Data.LoginHistory", b =>
                {
                    b.Property<Guid>("LoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoginId")
                        .HasName("PK__LoginHis__C9F84E0D1A2B3F4D");

                    b.ToTable("LoginHistory", (string)null);
                });

            modelBuilder.Entity("HR_KD.Data.MucLuongCoSo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("LuongCoSo")
                        .HasColumnType("decimal(18,0)");

                    b.Property<DateTime?>("NgayHetHieuLuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayHieuLuc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MucLuongCoSos");
                });

            modelBuilder.Entity("HR_KD.Data.MucLuongToiThieuVung", b =>
                {
                    b.Property<int>("VungLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VungLuong"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MucLuongToiThieuGio")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("MucLuongToiThieuThang")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("VungLuong");

                    b.ToTable("MucLuongToiThieuVungs");
                });

            modelBuilder.Entity("HR_KD.Data.NgayLe", b =>
                {
                    b.Property<int>("MaNgayLe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNgayLe"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("NgayLe1")
                        .HasColumnType("date")
                        .HasColumnName("NgayLe");

                    b.Property<int?>("SoNgayNghi")
                        .HasColumnType("int");

                    b.Property<string>("TenNgayLe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNgayLe")
                        .HasName("PK__NgayLe__55131492858AED82");

                    b.ToTable("NgayLe", (string)null);
                });

            modelBuilder.Entity("HR_KD.Data.NgayNghi", b =>
                {
                    b.Property<int>("MaNgayNghi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNgayNghi"));

                    b.Property<string>("FileDinhKem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyDo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaLoaiNgayNghi")
                        .HasColumnType("int");

                    b.Property<int>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    b.Property<DateTime>("NgayDuyet")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayLamDon")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("NgayNghi1")
                        .HasColumnType("date")
                        .HasColumnName("NgayNghi");

                    b.Property<int?>("NguoiDuyetId")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chưa Duyệt");

                    b.HasKey("MaNgayNghi")
                        .HasName("PK__NgayNghi__526A7F783CFC0001");

                    b.HasIndex("MaLoaiNgayNghi");

                    b.HasIndex("MaNv");

                    b.HasIndex("NguoiDuyetId");

                    b.ToTable("NgayNghi", null, t =>
                        {
                            t.HasTrigger("trg_UpdateSoDuPhep");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("HR_KD.Data.NhanVien", b =>
                {
                    b.Property<int>("MaNv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNv"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaChucVu")
                        .HasColumnType("int");

                    b.Property<int>("MaPhongBan")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayVaoLam")
                        .HasColumnType("date");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SDT");

                    b.Property<string>("TrinhDoHocVan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaNv")
                        .HasName("PK__NhanVien__2725D70A275D256C");

                    b.HasIndex("MaChucVu");

                    b.HasIndex("MaPhongBan");

                    b.HasIndex(new[] { "Email" }, "UQ__NhanVien__A9D10534AE786C7D")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("HR_KD.Data.PhongBan", b =>
                {
                    b.Property<int>("MaPhongBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhongBan"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenPhongBan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaPhongBan")
                        .HasName("PK__PhongBan__D0910CC8615D7A9E");

                    b.ToTable("PhongBan", (string)null);
                });

            modelBuilder.Entity("HR_KD.Data.QuyenHan", b =>
                {
                    b.Property<string>("MaQuyenHan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTaQuyenHan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenQuyenHan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaQuyenHan")
                        .HasName("PK__QuyenHan__3EAF3EE647B2787F");

                    b.ToTable("QuyenHan", (string)null);
                });

            modelBuilder.Entity("HR_KD.Data.SalaryStatistic", b =>
                {
                    b.Property<int>("MaThongKe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongKe"));

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<decimal?>("TongBhxh")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("TongBHXH");

                    b.Property<decimal?>("TongLuong")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("TongThucNhan")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("TongTncn")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("TongTNCN");

                    b.HasKey("MaThongKe")
                        .HasName("PK__SalarySt__60E521F4040BFD95");

                    b.ToTable("SalaryStatistics");
                });

            modelBuilder.Entity("HR_KD.Data.SoDuPhep", b =>
                {
                    b.Property<int>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoNgayConLai")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("MaNv", "Nam")
                        .HasName("PK__SoDuPhep__070385985BD7438C");

                    b.ToTable("SoDuPhep", (string)null);
                });

            modelBuilder.Entity("HR_KD.Data.TaiKhoan", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username")
                        .HasName("PK__TaiKhoan__536C85E5C4E86E6E");

                    b.HasIndex("MaNv");

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("HR_KD.Data.TaiKhoanNganHang", b =>
                {
                    b.Property<int>("MaTk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaTK");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTk"));

                    b.Property<string>("ChiNhanh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    b.Property<string>("SoTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenNganHang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaTk")
                        .HasName("PK__TaiKhoan__27250070144A40C2");

                    b.HasIndex("MaNv");

                    b.HasIndex(new[] { "SoTaiKhoan" }, "UQ__TaiKhoan__E619229B413F90EC")
                        .IsUnique();

                    b.ToTable("TaiKhoanNganHang", (string)null);
                });

            modelBuilder.Entity("HR_KD.Data.TaiKhoanQuyenHan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaQuyenHan")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MaQuyenHan");

                    b.HasIndex("Username");

                    b.ToTable("TaiKhoanQuyenHans");
                });

            modelBuilder.Entity("HR_KD.Data.TangCa", b =>
                {
                    b.Property<int>("MaTangCa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTangCa"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    b.Property<DateOnly>("NgayTangCa")
                        .HasColumnType("date");

                    b.Property<decimal>("SoGioTangCa")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chưa Duyệt");

                    b.Property<decimal>("TyLeTangCa")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("MaTangCa")
                        .HasName("PK__TangCa__B3E1C5497A40A099");

                    b.HasIndex("MaNv");

                    b.ToTable("TangCa", (string)null);
                });

            modelBuilder.Entity("HR_KD.Data.ThongBao", b =>
                {
                    b.Property<int>("MaThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongBao"));

                    b.Property<bool?>("DaDoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LoaiThongBao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    b.Property<DateTime?>("NgayThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaThongBao")
                        .HasName("PK__ThongBao__04DEB54EF0F2502F");

                    b.HasIndex("MaNv");

                    b.ToTable("ThongBao", (string)null);
                });

            modelBuilder.Entity("HR_KD.Data.ThongTinBaoHiem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LoaiBaoHiem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MucLuongCoSoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayHetHieuLuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayHieuLuc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TyLeNguoiLaoDong")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TyLeNhaTuyenDung")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("VungLuongTheoDiaPhuongId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MucLuongCoSoId");

                    b.HasIndex("VungLuongTheoDiaPhuongId");

                    b.ToTable("ThongTinBaoHiems");
                });

            modelBuilder.Entity("HR_KD.Data.ThongTinLuongNV", b =>
                {
                    b.Property<int>("MaLuongNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLuongNV"));

                    b.Property<decimal>("BHTN")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BHXH")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BHYT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LuongCoBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaNv")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayApDung")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PhuCapCoDinh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ThuongCoDinh")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaLuongNV");

                    b.HasIndex("MaNv");

                    b.ToTable("ThongTinLuongNVs");
                });

            modelBuilder.Entity("HR_KD.Data.TieuChiDanhGiaFullTime", b =>
                {
                    b.Property<int>("MaTieuChiDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTieuChiDanhGia"));

                    b.Property<decimal?>("DiemDanhGia")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("MaDanhGia")
                        .HasColumnType("int");

                    b.Property<string>("MoTaDanhGia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDanhGia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaTieuChiDanhGia")
                        .HasName("PK__TieuChiD__F90598A0F25A7704");

                    b.HasIndex("MaDanhGia");

                    b.ToTable("TieuChiDanhGiaFullTime", (string)null);
                });

            modelBuilder.Entity("HR_KD.Data.TieuChiDanhGiaPartTime", b =>
                {
                    b.Property<int>("MaTieuChiDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTieuChiDanhGia"));

                    b.Property<decimal>("DiemDanhGia")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("MoTaDanhGia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDanhGia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaTieuChiDanhGia")
                        .HasName("PK__TieuChiD__F90598A054481BC4");

                    b.ToTable("TieuChiDanhGiaPartTime", (string)null);
                });

            modelBuilder.Entity("HR_KD.Data.VungLuongTheoDiaPhuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("QuanHuyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TinhThanh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("VungLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VungLuong");

                    b.ToTable("VungLuongTheoDiaPhuongs");
                });

            modelBuilder.Entity("HR_KD.Data.YeuCauSuaChamCong", b =>
                {
                    b.Property<int>("MaYeuCau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaYeuCau"));

                    b.Property<TimeOnly?>("GioRaMoi")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("GioVaoMoi")
                        .HasColumnType("time");

                    b.Property<string>("LyDo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    b.Property<DateOnly>("NgayLamViec")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayYeuCau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("TongGio")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaYeuCau")
                        .HasName("PK__YeuCauSu__CFA5DF4EB14CB029");

                    b.HasIndex("MaNv");

                    b.ToTable("YeuCauSuaChamCong", (string)null);
                });

            modelBuilder.Entity("HopDongLaoDong", b =>
                {
                    b.Property<int>("MaHopDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHopDong"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LyDoNghiViec")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaLoaiHopDong")
                        .HasColumnType("int");

                    b.Property<int>("MaNv")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayNghiViec")
                        .HasColumnType("date");

                    b.Property<int?>("SoLanGiaHan")
                        .HasColumnType("int");

                    b.Property<int?>("ThoiHan")
                        .HasColumnType("int");

                    b.HasKey("MaHopDong");

                    b.HasIndex("MaLoaiHopDong");

                    b.HasIndex("MaNv");

                    b.ToTable("HopDongLaoDongs");
                });

            modelBuilder.Entity("HR_KD.Data.BangLuong", b =>
                {
                    b.HasOne("HR_KD.Data.NhanVien", "MaNvNavigation")
                        .WithMany("BangLuongs")
                        .HasForeignKey("MaNv")
                        .IsRequired()
                        .HasConstraintName("FK__BangLuong__MaNV__60A75C0F");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("HR_KD.Data.ChamCong", b =>
                {
                    b.HasOne("HR_KD.Data.NhanVien", "MaNvNavigation")
                        .WithMany("ChamCongs")
                        .HasForeignKey("MaNv")
                        .IsRequired()
                        .HasConstraintName("FK__ChamCong__MaNV__48CFD27E");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("HR_KD.Data.ChiTietDanhGium", b =>
                {
                    b.HasOne("HR_KD.Data.DanhGiaNhanVien", "MaDanhGiaNavigation")
                        .WithMany("ChiTietDanhGia")
                        .HasForeignKey("MaDanhGia")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDa__MaDan__6EF57B66");

                    b.HasOne("HR_KD.Data.TieuChiDanhGiaFullTime", "MaTieuChiDanhGiaNavigation")
                        .WithMany("ChiTietDanhGia")
                        .HasForeignKey("MaTieuChiDanhGia")
                        .HasConstraintName("FK__ChiTietDa__MaTie__6FE99F9F");

                    b.Navigation("MaDanhGiaNavigation");

                    b.Navigation("MaTieuChiDanhGiaNavigation");
                });

            modelBuilder.Entity("HR_KD.Data.DanhGiaNhanVien", b =>
                {
                    b.HasOne("HR_KD.Data.NhanVien", "MaNguoiDanhGiaNavigation")
                        .WithMany("DanhGiaNhanViens")
                        .HasForeignKey("MaNguoiDanhGia")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__DanhGiaNh__MaNgu__656C112C");

                    b.Navigation("MaNguoiDanhGiaNavigation");
                });

            modelBuilder.Entity("HR_KD.Data.DaoTao", b =>
                {
                    b.HasOne("HR_KD.Data.PhongBan", "PhongBan")
                        .WithMany("DaoTaos")
                        .HasForeignKey("MaPhongBan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("HR_KD.Data.LichSuChamCong", b =>
                {
                    b.HasOne("HR_KD.Data.NhanVien", "MaNvNavigation")
                        .WithMany("LichSuChamCongs")
                        .HasForeignKey("MaNv")
                        .IsRequired()
                        .HasConstraintName("FK__LichSuCham__MaNV__4CA06362");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("HR_KD.Data.LichSuDaoTao", b =>
                {
                    b.HasOne("HR_KD.Data.DaoTao", "MaDaoTaoNavigation")
                        .WithMany("LichSuDaoTaos")
                        .HasForeignKey("MaDaoTao")
                        .IsRequired()
                        .HasConstraintName("FK__LichSuDao__MaDao__7C4F7684");

                    b.HasOne("HR_KD.Data.NhanVien", "MaNvNavigation")
                        .WithMany("LichSuDaoTaos")
                        .HasForeignKey("MaNv")
                        .IsRequired()
                        .HasConstraintName("FK__LichSuDaoT__MaNV__7B5B524B");

                    b.Navigation("MaDaoTaoNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("HR_KD.Data.NgayNghi", b =>
                {
                    b.HasOne("HR_KD.Data.LoaiNgayNghi", "MaLoaiNgayNghiNavigation")
                        .WithMany("NgayNghis")
                        .HasForeignKey("MaLoaiNgayNghi")
                        .HasConstraintName("FK__NgayNghi__MaLoai__5165187F");

                    b.HasOne("HR_KD.Data.NhanVien", "MaNvNavigation")
                        .WithMany("NgayNghis")
                        .HasForeignKey("MaNv")
                        .IsRequired()
                        .HasConstraintName("FK__NgayNghi__MaNV__5070F446");

                    b.HasOne("HR_KD.Data.NhanVien", "NguoiDuyet")
                        .WithMany()
                        .HasForeignKey("NguoiDuyetId");

                    b.Navigation("MaLoaiNgayNghiNavigation");

                    b.Navigation("MaNvNavigation");

                    b.Navigation("NguoiDuyet");
                });

            modelBuilder.Entity("HR_KD.Data.NhanVien", b =>
                {
                    b.HasOne("HR_KD.Data.ChucVu", "MaChucVuNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaChucVu")
                        .IsRequired()
                        .HasConstraintName("FK__NhanVien__MaChuc__3D5E1FD2");

                    b.HasOne("HR_KD.Data.PhongBan", "MaPhongBanNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaPhongBan")
                        .IsRequired()
                        .HasConstraintName("FK__NhanVien__MaPhon__3C69FB99");

                    b.Navigation("MaChucVuNavigation");

                    b.Navigation("MaPhongBanNavigation");
                });

            modelBuilder.Entity("HR_KD.Data.SoDuPhep", b =>
                {
                    b.HasOne("HR_KD.Data.NhanVien", "MaNvNavigation")
                        .WithMany("SoDuPheps")
                        .HasForeignKey("MaNv")
                        .IsRequired()
                        .HasConstraintName("FK__SoDuPhep__MaNV__5441852A");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("HR_KD.Data.TaiKhoan", b =>
                {
                    b.HasOne("HR_KD.Data.NhanVien", "MaNvNavigation")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("MaNv")
                        .IsRequired()
                        .HasConstraintName("FK__TaiKhoan__MaNV__4222D4EF");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("HR_KD.Data.TaiKhoanNganHang", b =>
                {
                    b.HasOne("HR_KD.Data.NhanVien", "MaNvNavigation")
                        .WithMany("TaiKhoanNganHangs")
                        .HasForeignKey("MaNv")
                        .IsRequired()
                        .HasConstraintName("FK__TaiKhoanNg__MaNV__5AEE82B9");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("HR_KD.Data.TaiKhoanQuyenHan", b =>
                {
                    b.HasOne("HR_KD.Data.QuyenHan", "QuyenHan")
                        .WithMany("TaiKhoanQuyenHans")
                        .HasForeignKey("MaQuyenHan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR_KD.Data.TaiKhoan", "TaiKhoan")
                        .WithMany("TaiKhoanQuyenHans")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuyenHan");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("HR_KD.Data.TangCa", b =>
                {
                    b.HasOne("HR_KD.Data.NhanVien", "MaNvNavigation")
                        .WithMany("TangCas")
                        .HasForeignKey("MaNv")
                        .IsRequired()
                        .HasConstraintName("FK__TangCa__MaNV__693CA210");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("HR_KD.Data.ThongBao", b =>
                {
                    b.HasOne("HR_KD.Data.NhanVien", "MaNvNavigation")
                        .WithMany("ThongBaos")
                        .HasForeignKey("MaNv")
                        .HasConstraintName("FK__ThongBao__MaNV__01142BA1");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("HR_KD.Data.ThongTinBaoHiem", b =>
                {
                    b.HasOne("HR_KD.Data.MucLuongCoSo", "MucLuongCoSo")
                        .WithMany()
                        .HasForeignKey("MucLuongCoSoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR_KD.Data.VungLuongTheoDiaPhuong", "VungLuongTheoDiaPhuong")
                        .WithMany()
                        .HasForeignKey("VungLuongTheoDiaPhuongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MucLuongCoSo");

                    b.Navigation("VungLuongTheoDiaPhuong");
                });

            modelBuilder.Entity("HR_KD.Data.ThongTinLuongNV", b =>
                {
                    b.HasOne("HR_KD.Data.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HR_KD.Data.TieuChiDanhGiaFullTime", b =>
                {
                    b.HasOne("HR_KD.Data.DanhGiaNhanVien", "MaDanhGiaNavigation")
                        .WithMany("TieuChiDanhGiaFullTimes")
                        .HasForeignKey("MaDanhGia")
                        .IsRequired()
                        .HasConstraintName("FK__TieuChiDa__MaDan__6C190EBB");

                    b.Navigation("MaDanhGiaNavigation");
                });

            modelBuilder.Entity("HR_KD.Data.VungLuongTheoDiaPhuong", b =>
                {
                    b.HasOne("HR_KD.Data.MucLuongToiThieuVung", "MucLuongVung")
                        .WithMany()
                        .HasForeignKey("VungLuong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MucLuongVung");
                });

            modelBuilder.Entity("HR_KD.Data.YeuCauSuaChamCong", b =>
                {
                    b.HasOne("HR_KD.Data.NhanVien", "MaNvNavigation")
                        .WithMany("YeuCauSuaChamCongs")
                        .HasForeignKey("MaNv")
                        .IsRequired()
                        .HasConstraintName("FK__YeuCauSuaC__MaNV__76969D2E");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("HopDongLaoDong", b =>
                {
                    b.HasOne("HR_KD.Data.LoaiHopDong", "LoaiHopDong")
                        .WithMany()
                        .HasForeignKey("MaLoaiHopDong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR_KD.Data.NhanVien", "NhanVien")
                        .WithMany("HopDongLaoDongs")
                        .HasForeignKey("MaNv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiHopDong");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HR_KD.Data.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("HR_KD.Data.DanhGiaNhanVien", b =>
                {
                    b.Navigation("ChiTietDanhGia");

                    b.Navigation("TieuChiDanhGiaFullTimes");
                });

            modelBuilder.Entity("HR_KD.Data.DaoTao", b =>
                {
                    b.Navigation("LichSuDaoTaos");
                });

            modelBuilder.Entity("HR_KD.Data.LoaiNgayNghi", b =>
                {
                    b.Navigation("NgayNghis");
                });

            modelBuilder.Entity("HR_KD.Data.NhanVien", b =>
                {
                    b.Navigation("BangLuongs");

                    b.Navigation("ChamCongs");

                    b.Navigation("DanhGiaNhanViens");

                    b.Navigation("HopDongLaoDongs");

                    b.Navigation("LichSuChamCongs");

                    b.Navigation("LichSuDaoTaos");

                    b.Navigation("NgayNghis");

                    b.Navigation("SoDuPheps");

                    b.Navigation("TaiKhoanNganHangs");

                    b.Navigation("TaiKhoans");

                    b.Navigation("TangCas");

                    b.Navigation("ThongBaos");

                    b.Navigation("YeuCauSuaChamCongs");
                });

            modelBuilder.Entity("HR_KD.Data.PhongBan", b =>
                {
                    b.Navigation("DaoTaos");

                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("HR_KD.Data.QuyenHan", b =>
                {
                    b.Navigation("TaiKhoanQuyenHans");
                });

            modelBuilder.Entity("HR_KD.Data.TaiKhoan", b =>
                {
                    b.Navigation("TaiKhoanQuyenHans");
                });

            modelBuilder.Entity("HR_KD.Data.TieuChiDanhGiaFullTime", b =>
                {
                    b.Navigation("ChiTietDanhGia");
                });
#pragma warning restore 612, 618
        }
    }
}
